#!/bin/zsh

WALLPAPER_DIR="$HOME/.config/hypr/wallpapers"

CONFIG_FILE="$HOME/.config/hypr/hyprpaper.conf"

echo "# Generated by the wallpaper-generator script" > "$CONFIG_FILE"

find "$WALLPAPER_DIR" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" \) -print0 | while IFS= read -r -d $'\0' file; do
  echo "preload = $file" >> "$CONFIG_FILE"
done

random_wallpaper=$(find "$WALLPAPER_DIR" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" \) -print0 | shuf -n1 -z | xargs -0)

if [ -n "$random_wallpaper" ]; then
  echo "wallpaper = ,$random_wallpaper" >> "$CONFIG_FILE"
else
  echo "No wallpapers found in $WALLPAPER_DIR. Using a default black background." >> "$CONFIG_FILE"
fi

echo "hyprpaper.conf has been generated and is ready to use!"

